version: '3.7'
services:
  demo-nginx:
    image: nginx
    container_name: demo-nginx
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - demo-api
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    links:
      - demo-api
  demo-api:
    build: ./../../
    image: nodejs
    container_name: demo-api
    env_file:
      - ".env"
    links:
      - demo-mongo
    ports:
      - "4000:4000"
    volumes:
      - ./../../.:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: unless-stopped
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=demo-mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    command: ./wait-for.sh demo-mongo:27017 -- npm run start-dev
  demo-mongo:
    image: mongo
    container_name: demo-mongo
    restart: unless-stopped
    env_file:
      - ".env"
    ports:
    - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB
    volumes:
      - demo-mongo-data:/data/db
volumes:
  demo-mongo-data:
  node_modules:
